dist: xenial
language: python
sudo: true
branches:
  only:
    - master

python:
  - 3.6
  - 3.7

env:
    - PYSAL_PYPI=true PYSAL_PLUS=true
    - PYSAL_PYPI=true PYSAL_PLUS=false
    - PYSAL_PYPI=false PYSAL_PLUS=true
    - PYSAL_PYPI=false PYSAL_PLUS=false


matrix:
  allow_failures:
    - python: 3.6
      env: PYSAL_PYPI=false PYSAL_PLUS=false
    - python: 3.6
      env: PYSAL_PYPI=false PYSAL_PLUS=true
    - python: 3.7
      env: PYSAL_PYPI=false PYSAL_PLUS=false
    - python: 3.7
      env: PYSAL_PYPI=false PYSAL_PLUS=true


before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --add channels conda-forge --force
  - conda config --set channel_priority strict
  - conda create -y --name test-env python=$TRAVIS_PYTHON_VERSION --file requirements.txt --file requirements_tests.txt
  - source activate test-env

install:
  - conda install --yes pip
  - if "$PYSAL_PYPI"; then
        echo 'testing pypi libpysal' && pip install libpysal;
    else
        echo 'testing git libpysal';
        pip install https://github.com/pysal/libpysal/archive/master.zip;
    fi;
  - if "PYSAL_PLUS"; then
        echo 'testing PLUS' && conda install --file requirements_plus.txt;
    fi;
  - pip install -r requirements_dev.txt

script:
  - python setup.py sdist >/dev/null
  - python setup.py install
  - nosetests --verbose --with-coverage --cover-package=spreg;
  #- cd doc; make pickle; make doctest
notifications:
    email:
        recipients:
            - sjsrey@gmail.com
            - levi.john.wolf@gmail.com
            - dfolch@gmail.com
            - daniel.arribas.bel@gmail.com
            - weikang9009@gmail.com
            - tayoshan@gmail.com
            - jgaboardi@gmail.com
            - phil.stphns@gmail.com
            - pedrovma@gmail.com
        on_success: change
        on_failure: change

after_success:
  - coveralls
